### ISSUE TITLE
No such file or directory 

### ISSUE THREAD

**Issue by CWood-sdf** [MordechaiHadad/bob#239] opened 2024-09-10 18:49 UTC
Im using arch linux. Whenever I try to change/update the neovim version, I get an error from bob saying "ERROR Error: No such file or directory (os error 2)". This happens only when I already have a neovim version in nvim-bin. I can fix this by running `rm ~/.local/share/bob/nvim-bin -rf`, then `bob use ...` works as expected. However, this is kinda annoying to have to delete nvim-bin before updating. 

This happens on both the install from the AUR and using `cargo install --git ...`

**Comment by MordechaiHadad** [comment] 2024-09-11 06:06
Hmm that is odd, when you stumble upon this error again can you show me the ls output of bob folder?

**Comment by MordechaiHadad** [comment] 2024-09-11 07:53
Hmmm I also got this error for a split second but it seems to be fixed with the last PR i created.

**Comment by CWood-sdf** [comment] 2024-09-11 15:33
I tried checking out the latest commit and building and it still has the same error

![maim-2024_09_11-11_32](https://github.com/user-attachments/assets/df46e158-62b4-457d-8bfc-22d12a4cf6b6)

This is what the ~/.local/share/bob file structure looks like from neotree

**Comment by MordechaiHadad** [comment] 2024-09-11 15:40
Ah fair was mostly a dumb guess, do you have any minimal steps I can do to reproduce this?

**Comment by CWood-sdf** [comment] 2024-09-11 15:43
for me it's just:

```sh
rm ~/.local/share/bob -rf

bob use nightly # this command works

bob use nightly # this command fails

bob use 0.9.0 # this command also fails
```

**Comment by CWood-sdf** [comment] 2024-09-11 17:07
ok i found the problematic line:

in use_handler.rs at line 209, there's this line:

```rs
        let output = Command::new("nvim").arg("--&bob").output()?.stdout;
```

The problem is that, for some reason, Command::new() cannot find the nvim executable.

Everything else works completely find when I replace the nvim with the absolute path to the .local/sharebob/nvim-bin/nvim executable

**Comment by MordechaiHadad** [comment] 2024-09-12 10:42
> ok i found the problematic line:
> 
> in use_handler.rs at line 209, there's this line:
> 
> ```rust
>         let output = Command::new("nvim").arg("--&bob").output()?.stdout;
> ```
> 
> The problem is that, for some reason, Command::new() cannot find the nvim executable.
> 
> Everything else works completely find when I replace the nvim with the absolute path to the .local/sharebob/nvim-bin/nvim executable
Okay so I tried now, yes it seems like because nvim isn't in ur $PATH it does this, I will change this to absolute path

**Comment by MordechaiHadad** [comment] 2024-09-12 10:51
fixed now

**Closed by MordechaiHadad** 2024-09-12 10:51 UTC
Labels: bug
