### ISSUE TITLE
Error: Couldn't create downloads directory

### ISSUE THREAD

**Issue by cheginit** [MordechaiHadad/bob#101] opened 2023-03-09 15:01 UTC
After updating to the latest version (2.1.0), I get this error:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/13016644/224063425-ba86faca-0361-4253-8f82-ef3f36adc41f.png">

I am on macOS. I didn't have this issue with 2.0. Also, I already have the new `bob` location:

<img width="261" alt="image" src="https://user-images.githubusercontent.com/13016644/224063993-660655b8-4ffe-4029-b9e0-d28412d1bec5.png">

Also, I do not have any config file.

**Comment by cheginit** [comment] 2023-03-09 18:25
I couldn't find the binary file in the link that you sent, can you give me the direct link to the finle?

**Comment by marcomayer** [comment] 2023-03-10 10:22
Got the same issue since upgrading to 2.1 on latest macOS:
```
❯ bob install nightly
ERROR Error: Couldn't create downloads directory
❯ bob list
ERROR Error: Couldn't create downloads directory
```

**Comment by MordechaiHadad** [comment] 2023-03-10 10:24
> I couldn't find the binary file in the link that you sent, can you give me the direct link to the finle?

https://github.com/MordechaiHadad/bob/actions/runs/4375873244
scroll all the way down you will see a macos downloads file, here is the direct link https://github.com/MordechaiHadad/bob/suites/11457169685/artifacts/591112054

**Comment by MordechaiHadad** [comment] 2023-03-10 10:24
@marcomayer if you can test the testing binary also would be great help, want to push a hotfix asap

**Comment by utkarshgupta137** [comment] 2023-03-10 11:29
The problem is that it is using `/home/<user>` instead of `/User/<user>` on mac.

```
[16:57]❯ ./bob list
/home/utkarsh/.local/share/bob
Mar 10 16:57:40.013 ERROR Error: Couldn't create downloads directory
```

**Comment by utkarshgupta137** [comment] 2023-03-10 11:32
This seems to be the offending commit: https://github.com/MordechaiHadad/bob/commit/9b6290f5838b4b576897d06521e95befa2a50b0d

**Comment by MordechaiHadad** [comment] 2023-03-10 11:55
@utkarshgupta137 @marcomayer @cheginit should be fixed now 
https://github.com/MordechaiHadad/bob/suites/11478249610/artifacts/592669254

**Comment by utkarshgupta137** [comment] 2023-03-10 11:59
Nope. I tried artifacts from both https://github.com/MordechaiHadad/bob/actions/runs/4384186898 & https://github.com/MordechaiHadad/bob/actions/runs/4384197307

**Comment by MordechaiHadad** [comment] 2023-03-10 12:01
that doesn't make any sense, let me readd this debug print statement

**Comment by utkarshgupta137** [comment] 2023-03-10 12:26
> that doesn't make any sense, let me readd this debug print statement

I've raised a PR with a fix.
`cfg!(linux)` / `cfg!(macos)` don't exist which is used in your PR.
Ref: https://doc.rust-lang.org/reference/conditional-compilation.html#unix-and-windows

**Closed** 2023-03-10 12:37 UTC
Labels: bug

**Comment by MordechaiHadad** [comment] 2023-03-10 12:38
@utkarshgupta137 Thank you! I forgot you had to specify `target_os`
